executors:
  node:
    docker:
      - image: circleci/node:12.19.0
    working_directory: ~/app
jobs:
  build:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: yarn build
          name: Build the Typescript files
      - persist_to_workspace:
          paths:
            - app
          root: ~/
  check:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: |
            npx prettier --check \
              '**/*.md' \
              '**/*.json' \
              '**/*.ts' \
              '**/*.yml' \
              .prettierrc
          name: Check that each file is formatted appropriately
  setup:
    executor: node
    steps:
      - add_ssh_keys:
          fingerprints:
            - 2c:3d:60:ad:08:a8:6f:67:95:09:48:24:46:58:ed:f1
      - run:
          command: git config --global user.email "$USER_EMAIL"
          name: Setup git author email address
      - run:
          command: git config --global user.name "$USER_NAME"
          name: Setup git author name
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          name: Restores the Yarn package cache if possible
      - run:
          command: yarn install
          name: Install package dependencies
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          name: Saves the Yarn package cache
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          paths:
            - app
          root: ~/
  test:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: yarn test:cov
          name: Run unit tests with code
      - store_artifacts:
          path: coverage
      - run:
          command: yarn codecov
          name: Upload test coverage report to Codecov
version: 2.1
workflows:
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - check:
          requires:
            - setup
      - test:
          requires:
            - setup
  version: 2
